//go:build amd64

package strconv

import "unsafe"

// parse8SSE parses the 8 bytes at p (the caller guarantees at least 8 readable
// bytes) as eight ASCII decimal digits. It returns ok == 1 and the eight-digit
// value when every byte is '0'..'9', else ok == 0. Generated by go-asmgen
// (parse_gen.go), in parse_amd64.s.
func parse8SSE(p *byte) (val, ok uint64)

// parseDigitsSIMD parses s (1..maxFastDigits ASCII digits expected) using the
// 8-digit SSE kernel for as many whole 8-char groups as fit, then a scalar tail
// for the remainder. It returns ok == false on the first non-digit byte so the
// caller falls back to strconv.
//
// The kernel takes a *byte (via unsafe.StringData), so the hot path performs no
// []byte(s) allocation. The kernel reads 8 bytes, so it is only invoked while at
// least 8 bytes remain in s; the unsafe pointer therefore always stays in
// bounds of the string's backing array.
func parseDigitsSIMD(s string) (uint64, bool) {
	var v uint64
	i := 0
	n := len(s)
	if n >= 8 {
		base := unsafe.StringData(s)
		for n-i >= 8 {
			val, ok := parse8SSE((*byte)(unsafe.Add(unsafe.Pointer(base), i)))
			if ok == 0 {
				// A non-digit lies in this group; the scalar loop pinpoints it
				// (and likewise returns ok=false), keeping one code path.
				return parseScalar(s, i, v)
			}
			v = v*100000000 + val
			i += 8
		}
	}
	return parseScalar(s, i, v)
}
