//go:build amd64

package strconv

import "unsafe"

// parse16SSE parses the 16 bytes at p (the caller guarantees at least 16
// readable bytes) as sixteen ASCII decimal digits. It returns ok == 1 and the
// sixteen-digit value when every byte is '0'..'9', else ok == 0. Generated by
// go-asmgen (parse_gen.go), in parse_amd64.s.
func parse16SSE(p *byte) (val, ok uint64)

// parseDigitsSIMD parses s (minFastDigits..maxFastDigits ASCII digits expected)
// with a SINGLE 16-digit SSE kernel call for the first sixteen characters, then
// a short scalar tail (0..3 digits) for the remainder. It returns ok == false on
// the first non-digit byte so the caller falls back to strconv.
//
// The fast path is only ever entered for n in [minFastDigits, maxFastDigits] =
// [16, 19] (see strconv.go), so n >= 16 always holds here and the kernel's
// 16-byte load is always in bounds of the string's backing array. The single
// call (vs the previous two-call 8-digit loop) removes a whole CALL plus its
// register-spill / frame-reload overhead from the hot 16-digit case.
//
// The kernel takes a *byte (via unsafe.StringData), so the hot path performs no
// []byte(s) allocation.
func parseDigitsSIMD(s string) (uint64, bool) {
	n := len(s)
	if n < 16 {
		// Defensive: the wrappers never route shorter runs here, but keep the
		// scalar path correct for any direct caller (and the !amd64 build).
		return parseScalar(s, 0, 0)
	}
	base := unsafe.StringData(s)
	val, ok := parse16SSE(base)
	if ok == 0 {
		// A non-digit lies in the first sixteen bytes; the scalar loop pinpoints
		// it (and likewise returns ok=false), keeping one error code path.
		return parseScalar(s, 0, 0)
	}
	// Finish the 0..3-digit tail (n is 16..19) with the scalar loop.
	return parseScalar(s, 16, val)
}
