//go:build ppc64le

package strconv

import (
	"unsafe"

	"golang.org/x/sys/cpu"
)

// parse16 parses the 16 bytes at p (the caller guarantees at least 16 readable
// bytes) as sixteen ASCII decimal digits using the POWER VSX kernel. It returns
// ok == 1 and the sixteen-digit value when every byte is '0'..'9', else ok == 0.
// Generated by go-asmgen (parse_gen_ppc64.go), in parse_ppc64le.s. The kernel
// uses ISA-3.0 (POWER9) instructions (LXVB16X), which raise SIGILL on POWER8, so
// it runs only when hasVSX reports POWER9+.
func parse16(p *byte) (val, ok uint64)

// hasVSX is the dispatch flag. The generated kernel emits ISA-3.0 (POWER9) VSX
// instructions (LXVB16X) that are illegal on POWER8, so it is gated on POWER9
// detection; on POWER8 the SIMD fast paths fall back to the scalar digit loop.
// It is a var (not a const) so the dispatch test can also drive the no-SIMD
// fallback on a POWER9+ host.
var hasVSX = cpu.PPC64.IsPOWER9

// parseDigitsSIMD parses s (minFastDigits..maxFastDigits ASCII digits expected)
// with a single 16-digit VSX kernel call for the first sixteen characters, then
// a short scalar tail (0..3 digits) for the remainder. It returns ok == false on
// the first non-digit byte so the caller falls back to strconv.
//
// The fast path is only ever entered for n in [minFastDigits, maxFastDigits] =
// [16, 19] (see strconv.go), so n >= 16 always holds here and the kernel's
// 16-byte load is always in bounds of the string's backing array. The kernel
// takes a *byte (via unsafe.StringData), so the hot path performs no []byte(s)
// allocation. On POWER8 (no LXVB16X) the whole run goes to the scalar loop.
func parseDigitsSIMD(s string) (uint64, bool) {
	n := len(s)
	if !hasVSX || n < 16 {
		// POWER8 (no VSX kernel) or a defensively short run (the wrappers never
		// route shorter runs here): the scalar path is correct for any caller.
		return parseScalar(s, 0, 0)
	}
	base := unsafe.StringData(s)
	val, ok := parse16(base)
	if ok == 0 {
		// A non-digit lies in the first sixteen bytes; the scalar loop pinpoints
		// it (and likewise returns ok=false), keeping one error code path.
		return parseScalar(s, 0, 0)
	}
	// Finish the 0..3-digit tail (n is 16..19) with the scalar loop.
	return parseScalar(s, 16, val)
}

// parse16Window folds the 16 bytes at s[i:i+16] as decimal digits via the VSX
// kernel. The caller guarantees i+16 <= len(s). It returns ok == false (so the
// float fast path falls back) if any of those 16 bytes is not a decimal digit.
// On POWER8 (no LXVB16X) it folds the window with the scalar loop instead.
func parse16Window(s string, i int) (uint64, bool) {
	if !hasVSX {
		return parseScalar(s[i:i+16], 0, 0)
	}
	base := unsafe.StringData(s)
	p := (*byte)(unsafe.Add(unsafe.Pointer(base), i))
	val, ok := parse16(p)
	return val, ok == 1
}
