// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·parse8SSE(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), SI
	MOVQ (SI), X0
	MOVO X0, X1
	MOVOU subD<>+0(SB), X2
	PSUBB X2, X1
	MOVO X0, X3
	MOVOU cLo<>+0(SB), X4
	PCMPGTB X4, X3
	MOVOU cHi<>+0(SB), X4
	PCMPGTB X0, X4
	PAND X4, X3
	PCMPEQB X5, X5
	PXOR X5, X3
	PMOVMSKB X3, AX
	ANDL $0xFF, AX
	TESTL AX, AX
	JNZ bad
	MOVOU madd<>+0(SB), X2
	PMADDUBSW X2, X1
	MOVOU mul100<>+0(SB), X2
	PMULLW X2, X1
	PHADDW X1, X1
	PEXTRW $0, X1, AX
	PEXTRW $1, X1, DX
	IMULQ $10000, AX
	ADDQ DX, AX
	MOVQ AX, val+8(FP)
	MOVQ $1, AX
	MOVQ AX, ok+16(FP)
	RET
bad:
	XORQ AX, AX
	MOVQ AX, val+8(FP)
	MOVQ AX, ok+16(FP)
	RET

DATA cLo<>+0(SB)/1, $0x2f
DATA cLo<>+1(SB)/1, $0x2f
DATA cLo<>+2(SB)/1, $0x2f
DATA cLo<>+3(SB)/1, $0x2f
DATA cLo<>+4(SB)/1, $0x2f
DATA cLo<>+5(SB)/1, $0x2f
DATA cLo<>+6(SB)/1, $0x2f
DATA cLo<>+7(SB)/1, $0x2f
DATA cLo<>+8(SB)/1, $0x2f
DATA cLo<>+9(SB)/1, $0x2f
DATA cLo<>+10(SB)/1, $0x2f
DATA cLo<>+11(SB)/1, $0x2f
DATA cLo<>+12(SB)/1, $0x2f
DATA cLo<>+13(SB)/1, $0x2f
DATA cLo<>+14(SB)/1, $0x2f
DATA cLo<>+15(SB)/1, $0x2f
GLOBL cLo<>(SB), RODATA|NOPTR, $16

DATA cHi<>+0(SB)/1, $0x3a
DATA cHi<>+1(SB)/1, $0x3a
DATA cHi<>+2(SB)/1, $0x3a
DATA cHi<>+3(SB)/1, $0x3a
DATA cHi<>+4(SB)/1, $0x3a
DATA cHi<>+5(SB)/1, $0x3a
DATA cHi<>+6(SB)/1, $0x3a
DATA cHi<>+7(SB)/1, $0x3a
DATA cHi<>+8(SB)/1, $0x3a
DATA cHi<>+9(SB)/1, $0x3a
DATA cHi<>+10(SB)/1, $0x3a
DATA cHi<>+11(SB)/1, $0x3a
DATA cHi<>+12(SB)/1, $0x3a
DATA cHi<>+13(SB)/1, $0x3a
DATA cHi<>+14(SB)/1, $0x3a
DATA cHi<>+15(SB)/1, $0x3a
GLOBL cHi<>(SB), RODATA|NOPTR, $16

DATA subD<>+0(SB)/1, $0x30
DATA subD<>+1(SB)/1, $0x30
DATA subD<>+2(SB)/1, $0x30
DATA subD<>+3(SB)/1, $0x30
DATA subD<>+4(SB)/1, $0x30
DATA subD<>+5(SB)/1, $0x30
DATA subD<>+6(SB)/1, $0x30
DATA subD<>+7(SB)/1, $0x30
DATA subD<>+8(SB)/1, $0x30
DATA subD<>+9(SB)/1, $0x30
DATA subD<>+10(SB)/1, $0x30
DATA subD<>+11(SB)/1, $0x30
DATA subD<>+12(SB)/1, $0x30
DATA subD<>+13(SB)/1, $0x30
DATA subD<>+14(SB)/1, $0x30
DATA subD<>+15(SB)/1, $0x30
GLOBL subD<>(SB), RODATA|NOPTR, $16

DATA madd<>+0(SB)/1, $0x0a
DATA madd<>+1(SB)/1, $0x01
DATA madd<>+2(SB)/1, $0x0a
DATA madd<>+3(SB)/1, $0x01
DATA madd<>+4(SB)/1, $0x0a
DATA madd<>+5(SB)/1, $0x01
DATA madd<>+6(SB)/1, $0x0a
DATA madd<>+7(SB)/1, $0x01
DATA madd<>+8(SB)/1, $0x0a
DATA madd<>+9(SB)/1, $0x01
DATA madd<>+10(SB)/1, $0x0a
DATA madd<>+11(SB)/1, $0x01
DATA madd<>+12(SB)/1, $0x0a
DATA madd<>+13(SB)/1, $0x01
DATA madd<>+14(SB)/1, $0x0a
DATA madd<>+15(SB)/1, $0x01
GLOBL madd<>(SB), RODATA|NOPTR, $16

DATA mul100<>+0(SB)/1, $0x64
DATA mul100<>+1(SB)/1, $0x00
DATA mul100<>+2(SB)/1, $0x01
DATA mul100<>+3(SB)/1, $0x00
DATA mul100<>+4(SB)/1, $0x64
DATA mul100<>+5(SB)/1, $0x00
DATA mul100<>+6(SB)/1, $0x01
DATA mul100<>+7(SB)/1, $0x00
DATA mul100<>+8(SB)/1, $0x64
DATA mul100<>+9(SB)/1, $0x00
DATA mul100<>+10(SB)/1, $0x01
DATA mul100<>+11(SB)/1, $0x00
DATA mul100<>+12(SB)/1, $0x64
DATA mul100<>+13(SB)/1, $0x00
DATA mul100<>+14(SB)/1, $0x01
DATA mul100<>+15(SB)/1, $0x00
GLOBL mul100<>(SB), RODATA|NOPTR, $16

