// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·parse16(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R3
	LXVB16X (R3)(R0), VS32
	MOVD $subD<>(SB), R4
	LXVB16X (R4)(R0), VS33
	MOVD $nine<>(SB), R4
	LXVB16X (R4)(R0), VS34
	MOVD $w1b<>(SB), R4
	LXVB16X (R4)(R0), VS35
	MOVD $w2h<>(SB), R4
	LXVB16X (R4)(R0), VS36
	MOVD $w3w<>(SB), R4
	LXVB16X (R4)(R0), VS37
	VSUBUBM V0, V1, V0
	VCMPGTUB V0, V2, V6
	MFVSRD VS38, R5
	VSLDOI $8, V6, V6, V7
	MFVSRD VS39, R6
	OR R5, R6, R5
	CMP R5, $0
	BNE bad
	VMULEUB V0, V3, V8
	VMULOUB V0, V3, V9
	VADDUHM V8, V9, V10
	VMULEUH V10, V4, V11
	VMULOUH V10, V4, V12
	VADDUWM V11, V12, V13
	VMULEUW V13, V5, V14
	VMULOUW V13, V5, V15
	VADDUDM V14, V15, V16
	MFVSRD VS48, R5
	VSLDOI $8, V16, V16, V17
	MFVSRD VS49, R6
	MOVD $100000000, R7
	MULLD R7, R5, R5
	ADD R6, R5, R5
	MOVD R5, val+8(FP)
	MOVD $1, R5
	MOVD R5, ok+16(FP)
	RET
bad:
	MOVD $0, R5
	MOVD R5, val+8(FP)
	MOVD R5, ok+16(FP)
	RET

DATA subD<>+0(SB)/1, $0x30
DATA subD<>+1(SB)/1, $0x30
DATA subD<>+2(SB)/1, $0x30
DATA subD<>+3(SB)/1, $0x30
DATA subD<>+4(SB)/1, $0x30
DATA subD<>+5(SB)/1, $0x30
DATA subD<>+6(SB)/1, $0x30
DATA subD<>+7(SB)/1, $0x30
DATA subD<>+8(SB)/1, $0x30
DATA subD<>+9(SB)/1, $0x30
DATA subD<>+10(SB)/1, $0x30
DATA subD<>+11(SB)/1, $0x30
DATA subD<>+12(SB)/1, $0x30
DATA subD<>+13(SB)/1, $0x30
DATA subD<>+14(SB)/1, $0x30
DATA subD<>+15(SB)/1, $0x30
GLOBL subD<>(SB), RODATA|NOPTR, $16

DATA nine<>+0(SB)/1, $0x09
DATA nine<>+1(SB)/1, $0x09
DATA nine<>+2(SB)/1, $0x09
DATA nine<>+3(SB)/1, $0x09
DATA nine<>+4(SB)/1, $0x09
DATA nine<>+5(SB)/1, $0x09
DATA nine<>+6(SB)/1, $0x09
DATA nine<>+7(SB)/1, $0x09
DATA nine<>+8(SB)/1, $0x09
DATA nine<>+9(SB)/1, $0x09
DATA nine<>+10(SB)/1, $0x09
DATA nine<>+11(SB)/1, $0x09
DATA nine<>+12(SB)/1, $0x09
DATA nine<>+13(SB)/1, $0x09
DATA nine<>+14(SB)/1, $0x09
DATA nine<>+15(SB)/1, $0x09
GLOBL nine<>(SB), RODATA|NOPTR, $16

DATA w1b<>+0(SB)/1, $0x0a
DATA w1b<>+1(SB)/1, $0x01
DATA w1b<>+2(SB)/1, $0x0a
DATA w1b<>+3(SB)/1, $0x01
DATA w1b<>+4(SB)/1, $0x0a
DATA w1b<>+5(SB)/1, $0x01
DATA w1b<>+6(SB)/1, $0x0a
DATA w1b<>+7(SB)/1, $0x01
DATA w1b<>+8(SB)/1, $0x0a
DATA w1b<>+9(SB)/1, $0x01
DATA w1b<>+10(SB)/1, $0x0a
DATA w1b<>+11(SB)/1, $0x01
DATA w1b<>+12(SB)/1, $0x0a
DATA w1b<>+13(SB)/1, $0x01
DATA w1b<>+14(SB)/1, $0x0a
DATA w1b<>+15(SB)/1, $0x01
GLOBL w1b<>(SB), RODATA|NOPTR, $16

DATA w2h<>+0(SB)/1, $0x00
DATA w2h<>+1(SB)/1, $0x64
DATA w2h<>+2(SB)/1, $0x00
DATA w2h<>+3(SB)/1, $0x01
DATA w2h<>+4(SB)/1, $0x00
DATA w2h<>+5(SB)/1, $0x64
DATA w2h<>+6(SB)/1, $0x00
DATA w2h<>+7(SB)/1, $0x01
DATA w2h<>+8(SB)/1, $0x00
DATA w2h<>+9(SB)/1, $0x64
DATA w2h<>+10(SB)/1, $0x00
DATA w2h<>+11(SB)/1, $0x01
DATA w2h<>+12(SB)/1, $0x00
DATA w2h<>+13(SB)/1, $0x64
DATA w2h<>+14(SB)/1, $0x00
DATA w2h<>+15(SB)/1, $0x01
GLOBL w2h<>(SB), RODATA|NOPTR, $16

DATA w3w<>+0(SB)/1, $0x00
DATA w3w<>+1(SB)/1, $0x00
DATA w3w<>+2(SB)/1, $0x27
DATA w3w<>+3(SB)/1, $0x10
DATA w3w<>+4(SB)/1, $0x00
DATA w3w<>+5(SB)/1, $0x00
DATA w3w<>+6(SB)/1, $0x00
DATA w3w<>+7(SB)/1, $0x01
DATA w3w<>+8(SB)/1, $0x00
DATA w3w<>+9(SB)/1, $0x00
DATA w3w<>+10(SB)/1, $0x27
DATA w3w<>+11(SB)/1, $0x10
DATA w3w<>+12(SB)/1, $0x00
DATA w3w<>+13(SB)/1, $0x00
DATA w3w<>+14(SB)/1, $0x00
DATA w3w<>+15(SB)/1, $0x01
GLOBL w3w<>(SB), RODATA|NOPTR, $16

