// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·parse16(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R1
	VL (R1), V0
	MOVD $subD<>(SB), R2
	VL (R2), V1
	MOVD $nine<>(SB), R2
	VL (R2), V2
	MOVD $w1b<>(SB), R2
	VL (R2), V3
	MOVD $w2h<>(SB), R2
	VL (R2), V4
	MOVD $w3w<>(SB), R2
	VL (R2), V5
	VSB V1, V0, V0
	VCHLB V0, V2, V6
	VLGVG $0, V6, R3
	VLGVG $1, V6, R4
	OR R3, R4, R3
	CMPBNE R3, $0, bad
	VMLEB V0, V3, V7
	VMLOB V0, V3, V8
	VAH V7, V8, V9
	VMLEH V9, V4, V10
	VMLOH V9, V4, V11
	VAF V10, V11, V12
	VMLEF V12, V5, V13
	VMLOF V12, V5, V14
	VAG V13, V14, V15
	VLGVG $0, V15, R3
	VLGVG $1, V15, R4
	MOVD $100000000, R5
	MULLD R5, R3, R3
	ADD R4, R3, R3
	MOVD R3, val+8(FP)
	MOVD $1, R3
	MOVD R3, ok+16(FP)
	RET
bad:
	MOVD $0, R3
	MOVD R3, val+8(FP)
	MOVD R3, ok+16(FP)
	RET

DATA subD<>+0(SB)/1, $0x30
DATA subD<>+1(SB)/1, $0x30
DATA subD<>+2(SB)/1, $0x30
DATA subD<>+3(SB)/1, $0x30
DATA subD<>+4(SB)/1, $0x30
DATA subD<>+5(SB)/1, $0x30
DATA subD<>+6(SB)/1, $0x30
DATA subD<>+7(SB)/1, $0x30
DATA subD<>+8(SB)/1, $0x30
DATA subD<>+9(SB)/1, $0x30
DATA subD<>+10(SB)/1, $0x30
DATA subD<>+11(SB)/1, $0x30
DATA subD<>+12(SB)/1, $0x30
DATA subD<>+13(SB)/1, $0x30
DATA subD<>+14(SB)/1, $0x30
DATA subD<>+15(SB)/1, $0x30
GLOBL subD<>(SB), RODATA|NOPTR, $16

DATA nine<>+0(SB)/1, $0x09
DATA nine<>+1(SB)/1, $0x09
DATA nine<>+2(SB)/1, $0x09
DATA nine<>+3(SB)/1, $0x09
DATA nine<>+4(SB)/1, $0x09
DATA nine<>+5(SB)/1, $0x09
DATA nine<>+6(SB)/1, $0x09
DATA nine<>+7(SB)/1, $0x09
DATA nine<>+8(SB)/1, $0x09
DATA nine<>+9(SB)/1, $0x09
DATA nine<>+10(SB)/1, $0x09
DATA nine<>+11(SB)/1, $0x09
DATA nine<>+12(SB)/1, $0x09
DATA nine<>+13(SB)/1, $0x09
DATA nine<>+14(SB)/1, $0x09
DATA nine<>+15(SB)/1, $0x09
GLOBL nine<>(SB), RODATA|NOPTR, $16

DATA w1b<>+0(SB)/1, $0x0a
DATA w1b<>+1(SB)/1, $0x01
DATA w1b<>+2(SB)/1, $0x0a
DATA w1b<>+3(SB)/1, $0x01
DATA w1b<>+4(SB)/1, $0x0a
DATA w1b<>+5(SB)/1, $0x01
DATA w1b<>+6(SB)/1, $0x0a
DATA w1b<>+7(SB)/1, $0x01
DATA w1b<>+8(SB)/1, $0x0a
DATA w1b<>+9(SB)/1, $0x01
DATA w1b<>+10(SB)/1, $0x0a
DATA w1b<>+11(SB)/1, $0x01
DATA w1b<>+12(SB)/1, $0x0a
DATA w1b<>+13(SB)/1, $0x01
DATA w1b<>+14(SB)/1, $0x0a
DATA w1b<>+15(SB)/1, $0x01
GLOBL w1b<>(SB), RODATA|NOPTR, $16

DATA w2h<>+0(SB)/1, $0x00
DATA w2h<>+1(SB)/1, $0x64
DATA w2h<>+2(SB)/1, $0x00
DATA w2h<>+3(SB)/1, $0x01
DATA w2h<>+4(SB)/1, $0x00
DATA w2h<>+5(SB)/1, $0x64
DATA w2h<>+6(SB)/1, $0x00
DATA w2h<>+7(SB)/1, $0x01
DATA w2h<>+8(SB)/1, $0x00
DATA w2h<>+9(SB)/1, $0x64
DATA w2h<>+10(SB)/1, $0x00
DATA w2h<>+11(SB)/1, $0x01
DATA w2h<>+12(SB)/1, $0x00
DATA w2h<>+13(SB)/1, $0x64
DATA w2h<>+14(SB)/1, $0x00
DATA w2h<>+15(SB)/1, $0x01
GLOBL w2h<>(SB), RODATA|NOPTR, $16

DATA w3w<>+0(SB)/1, $0x00
DATA w3w<>+1(SB)/1, $0x00
DATA w3w<>+2(SB)/1, $0x27
DATA w3w<>+3(SB)/1, $0x10
DATA w3w<>+4(SB)/1, $0x00
DATA w3w<>+5(SB)/1, $0x00
DATA w3w<>+6(SB)/1, $0x00
DATA w3w<>+7(SB)/1, $0x01
DATA w3w<>+8(SB)/1, $0x00
DATA w3w<>+9(SB)/1, $0x00
DATA w3w<>+10(SB)/1, $0x27
DATA w3w<>+11(SB)/1, $0x10
DATA w3w<>+12(SB)/1, $0x00
DATA w3w<>+13(SB)/1, $0x00
DATA w3w<>+14(SB)/1, $0x00
DATA w3w<>+15(SB)/1, $0x01
GLOBL w3w<>(SB), RODATA|NOPTR, $16

