// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·parse16SSE(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), SI
	MOVOU (SI), X0
	MOVO X0, X3
	MOVOU cLo<>+0(SB), X4
	PCMPGTB X4, X3
	MOVOU cHi<>+0(SB), X4
	PCMPGTB X0, X4
	PAND X4, X3
	PMOVMSKB X3, AX
	CMPL AX, $0xFFFF
	JNE bad
	MOVOU subD<>+0(SB), X2
	PSUBB X2, X0
	MOVOU madd1<>+0(SB), X2
	PMADDUBSW X0, X2
	MOVOU madd2<>+0(SB), X4
	PMADDWL X4, X2
	MOVL X2, AX
	PEXTRD $1, X2, CX
	PEXTRD $2, X2, DX
	PEXTRD $3, X2, DI
	IMULQ $10000, AX
	ADDQ CX, AX
	IMULQ $10000, DX
	ADDQ DI, DX
	IMULQ $100000000, AX
	ADDQ DX, AX
	MOVQ AX, val+8(FP)
	MOVQ $1, AX
	MOVQ AX, ok+16(FP)
	RET
bad:
	XORQ AX, AX
	MOVQ AX, val+8(FP)
	MOVQ AX, ok+16(FP)
	RET

DATA cLo<>+0(SB)/1, $0x2f
DATA cLo<>+1(SB)/1, $0x2f
DATA cLo<>+2(SB)/1, $0x2f
DATA cLo<>+3(SB)/1, $0x2f
DATA cLo<>+4(SB)/1, $0x2f
DATA cLo<>+5(SB)/1, $0x2f
DATA cLo<>+6(SB)/1, $0x2f
DATA cLo<>+7(SB)/1, $0x2f
DATA cLo<>+8(SB)/1, $0x2f
DATA cLo<>+9(SB)/1, $0x2f
DATA cLo<>+10(SB)/1, $0x2f
DATA cLo<>+11(SB)/1, $0x2f
DATA cLo<>+12(SB)/1, $0x2f
DATA cLo<>+13(SB)/1, $0x2f
DATA cLo<>+14(SB)/1, $0x2f
DATA cLo<>+15(SB)/1, $0x2f
GLOBL cLo<>(SB), RODATA|NOPTR, $16

DATA cHi<>+0(SB)/1, $0x3a
DATA cHi<>+1(SB)/1, $0x3a
DATA cHi<>+2(SB)/1, $0x3a
DATA cHi<>+3(SB)/1, $0x3a
DATA cHi<>+4(SB)/1, $0x3a
DATA cHi<>+5(SB)/1, $0x3a
DATA cHi<>+6(SB)/1, $0x3a
DATA cHi<>+7(SB)/1, $0x3a
DATA cHi<>+8(SB)/1, $0x3a
DATA cHi<>+9(SB)/1, $0x3a
DATA cHi<>+10(SB)/1, $0x3a
DATA cHi<>+11(SB)/1, $0x3a
DATA cHi<>+12(SB)/1, $0x3a
DATA cHi<>+13(SB)/1, $0x3a
DATA cHi<>+14(SB)/1, $0x3a
DATA cHi<>+15(SB)/1, $0x3a
GLOBL cHi<>(SB), RODATA|NOPTR, $16

DATA subD<>+0(SB)/1, $0x30
DATA subD<>+1(SB)/1, $0x30
DATA subD<>+2(SB)/1, $0x30
DATA subD<>+3(SB)/1, $0x30
DATA subD<>+4(SB)/1, $0x30
DATA subD<>+5(SB)/1, $0x30
DATA subD<>+6(SB)/1, $0x30
DATA subD<>+7(SB)/1, $0x30
DATA subD<>+8(SB)/1, $0x30
DATA subD<>+9(SB)/1, $0x30
DATA subD<>+10(SB)/1, $0x30
DATA subD<>+11(SB)/1, $0x30
DATA subD<>+12(SB)/1, $0x30
DATA subD<>+13(SB)/1, $0x30
DATA subD<>+14(SB)/1, $0x30
DATA subD<>+15(SB)/1, $0x30
GLOBL subD<>(SB), RODATA|NOPTR, $16

DATA madd1<>+0(SB)/1, $0x0a
DATA madd1<>+1(SB)/1, $0x01
DATA madd1<>+2(SB)/1, $0x0a
DATA madd1<>+3(SB)/1, $0x01
DATA madd1<>+4(SB)/1, $0x0a
DATA madd1<>+5(SB)/1, $0x01
DATA madd1<>+6(SB)/1, $0x0a
DATA madd1<>+7(SB)/1, $0x01
DATA madd1<>+8(SB)/1, $0x0a
DATA madd1<>+9(SB)/1, $0x01
DATA madd1<>+10(SB)/1, $0x0a
DATA madd1<>+11(SB)/1, $0x01
DATA madd1<>+12(SB)/1, $0x0a
DATA madd1<>+13(SB)/1, $0x01
DATA madd1<>+14(SB)/1, $0x0a
DATA madd1<>+15(SB)/1, $0x01
GLOBL madd1<>(SB), RODATA|NOPTR, $16

DATA madd2<>+0(SB)/1, $0x64
DATA madd2<>+1(SB)/1, $0x00
DATA madd2<>+2(SB)/1, $0x01
DATA madd2<>+3(SB)/1, $0x00
DATA madd2<>+4(SB)/1, $0x64
DATA madd2<>+5(SB)/1, $0x00
DATA madd2<>+6(SB)/1, $0x01
DATA madd2<>+7(SB)/1, $0x00
DATA madd2<>+8(SB)/1, $0x64
DATA madd2<>+9(SB)/1, $0x00
DATA madd2<>+10(SB)/1, $0x01
DATA madd2<>+11(SB)/1, $0x00
DATA madd2<>+12(SB)/1, $0x64
DATA madd2<>+13(SB)/1, $0x00
DATA madd2<>+14(SB)/1, $0x01
DATA madd2<>+15(SB)/1, $0x00
GLOBL madd2<>(SB), RODATA|NOPTR, $16

