//go:build s390x

package strconv

import "unsafe"

// parse16 parses the 16 bytes at p (the caller guarantees at least 16 readable
// bytes) as sixteen ASCII decimal digits using the z/Architecture vector-facility
// kernel. It returns ok == 1 and the sixteen-digit value when every byte is
// '0'..'9', else ok == 0. Generated by go-asmgen (parse_gen_s390x.go), in
// parse_s390x.s.
func parse16(p *byte) (val, ok uint64)

// parseDigitsSIMD parses s (minFastDigits..maxFastDigits ASCII digits expected)
// with a single 16-digit vector kernel call for the first sixteen characters,
// then a short scalar tail (0..3 digits) for the remainder. It returns ok ==
// false on the first non-digit byte so the caller falls back to strconv.
//
// The fast path is only ever entered for n in [minFastDigits, maxFastDigits] =
// [16, 19] (see strconv.go), so n >= 16 always holds here and the kernel's
// 16-byte load is always in bounds of the string's backing array. The kernel
// takes a *byte (via unsafe.StringData), so the hot path performs no []byte(s)
// allocation.
func parseDigitsSIMD(s string) (uint64, bool) {
	n := len(s)
	if n < 16 {
		// Defensive: the wrappers never route shorter runs here, but keep the
		// scalar path correct for any direct caller.
		return parseScalar(s, 0, 0)
	}
	base := unsafe.StringData(s)
	val, ok := parse16(base)
	if ok == 0 {
		// A non-digit lies in the first sixteen bytes; the scalar loop pinpoints
		// it (and likewise returns ok=false), keeping one error code path.
		return parseScalar(s, 0, 0)
	}
	// Finish the 0..3-digit tail (n is 16..19) with the scalar loop.
	return parseScalar(s, 16, val)
}

// parse16Window folds the 16 bytes at s[i:i+16] as decimal digits via the vector
// kernel. The caller guarantees i+16 <= len(s). It returns ok == false (so the
// float fast path falls back) if any of those 16 bytes is not a decimal digit.
func parse16Window(s string, i int) (uint64, bool) {
	base := unsafe.StringData(s)
	p := (*byte)(unsafe.Add(unsafe.Pointer(base), i))
	val, ok := parse16(p)
	return val, ok == 1
}
