// Package strconv is a drop-in fast path for base-10 integer parsing whose
// results — both the value AND any error — are byte-identical to the standard
// library's strconv. A SIMD kernel generated by go-asmgen (amd64 SSE; other
// architectures use a tight scalar loop) accelerates the common, hot case: a
// clean run of ASCII decimal digits (with an optional leading sign for the
// signed parsers), base 10, that fits the requested bitSize without overflow.
//
// Correctness is paramount. The fast path is taken ONLY for that unambiguous
// case and only ever returns a nil error; ANYTHING else (other bases, base
// prefixes, '_' digit separators, empty input, a non-digit byte, overflow,
// over-long input, unusual bitSizes) is delegated verbatim to the standard
// library, so the returned value and the exact *strconv.NumError (Func, quoted
// Num, ErrSyntax/ErrRange/...) match strconv bit for bit. FuzzParseUint,
// FuzzAtoi and FuzzParseInt assert that equivalence against strconv on
// arbitrary input.
package strconv

import "strconv"

// maxFastDigits is the largest number of decimal digits we accept on the fast
// path. 19 digits (<= 9_999_999_999_999_999_999) always fit in uint64; 20-digit
// inputs may or may not overflow, so we leave those to the standard library to
// reproduce its exact MaxUint64 / ErrRange behaviour.
const maxFastDigits = 19

// minFastDigits is the shortest digit run we route through the SIMD kernel for
// ParseUint / ParseInt. The kernel reads and folds a full 16-byte group per call
// (a real CALL, not inlined), so it needs at least sixteen digits present; for
// shorter strings there is no 16-byte group to vectorise and the standard
// library's tight inlined scalar loop is faster anyway. Benchmarks (native
// amd64) show the single-call 16-digit kernel overtakes strconv.ParseUint at 16
// digits and widens through 19; below this floor we delegate to strconv, which
// is both correct AND faster, so the package never regresses. Correctness is
// unaffected: the fallback is the real strconv, so value and error stay
// byte-identical either way.
const minFastDigits = 16

// minAtoiDigits is the Atoi-specific floor. strconv.Atoi has an *inlined*
// digit-at-a-time fast path for inputs shorter than 19 digits (on 64-bit), which
// the assembly-CALL SIMD kernel cannot beat; only at exactly 19 digits does
// strconv.Atoi fall back to its slower strconv.ParseInt path, where SIMD wins.
// So Atoi takes the SIMD path only at 19 digits and delegates otherwise — again
// never a regression.
const minAtoiDigits = 19

// ParseUint is a drop-in for strconv.ParseUint: identical value and error.
//
// Fast path: base == 10 (or the equivalent base == 0 with no prefix is left to
// strconv), bitSize covering the parsed value, and s a pure run of 1..19 ASCII
// decimal digits. Everything else falls back to strconv.
func ParseUint(s string, base, bitSize int) (uint64, error) {
	if base == 10 && (bitSize == 0 || bitSize == 64) && len(s) >= minFastDigits && len(s) <= maxFastDigits {
		if v, ok := parseDigits(s); ok {
			return v, nil
		}
	}
	return strconv.ParseUint(s, base, bitSize)
}

// ParseInt is a drop-in for strconv.ParseInt: identical value and error.
//
// Fast path: base 10, bitSize 0/64, optional leading '+'/'-', then a pure run of
// 1..19 decimal digits whose signed value fits int64. Everything else (other
// bases, bit sizes, overflow, syntax errors) falls back to strconv.
func ParseInt(s string, base, bitSize int) (int64, error) {
	if base == 10 && (bitSize == 0 || bitSize == 64) {
		body := s
		neg := false
		if len(body) >= 1 && (body[0] == '+' || body[0] == '-') {
			neg = body[0] == '-'
			body = body[1:]
		}
		if len(body) >= minFastDigits && len(body) <= maxFastDigits {
			if v, ok := parseDigits(body); ok {
				// v <= 9_999_999_999_999_999_999 < 1<<63 only when <= 18 digits
				// or 19 digits below the int64 cap; guard the signed range so
				// MaxInt64/MinInt64 boundaries fall back for exact ErrRange.
				if !neg && v <= 1<<63-1 {
					return int64(v), nil
				}
				if neg && v <= 1<<63 {
					return -int64(v), nil
				}
			}
		}
	}
	return strconv.ParseInt(s, base, bitSize)
}

// Atoi is a drop-in for strconv.Atoi: identical value and error.
//
// Fast path: optional leading '+'/'-', then a pure run of 1..19 decimal digits
// fitting int. Everything else falls back to strconv.
func Atoi(s string) (int, error) {
	body := s
	neg := false
	if len(body) >= 1 && (body[0] == '+' || body[0] == '-') {
		neg = body[0] == '-'
		body = body[1:]
	}
	if len(body) >= minAtoiDigits && len(body) <= maxFastDigits {
		if v, ok := parseDigits(body); ok {
			if !neg && v <= uint64(maxInt) {
				return int(v), nil
			}
			if neg && v <= uint64(maxInt)+1 {
				return -int(v), nil
			}
		}
	}
	return strconv.Atoi(s)
}

const maxInt = int(^uint(0) >> 1)

// parseDigits parses s, a string of 1..maxFastDigits bytes, as an unsigned
// base-10 value. It returns ok == false (and an unspecified value) if any byte
// is not an ASCII decimal digit, leaving the caller to fall back to strconv. The
// length bound guarantees the accumulated value cannot overflow uint64, so when
// ok is true the value is exact.
//
// It uses the SIMD 16-digit kernel for the bulk on amd64 (see parseDigitsSIMD)
// and a digit-at-a-time scalar loop for the short remainder and on other
// architectures.
func parseDigits(s string) (uint64, bool) {
	return parseDigitsSIMD(s)
}

// parseScalar parses s[i:] one digit at a time into the running value v. It is
// the architecture-independent core, also used to finish the 0..3-digit tail
// after the SIMD kernel has consumed the leading 16-digit group.
func parseScalar(s string, i int, v uint64) (uint64, bool) {
	for ; i < len(s); i++ {
		d := s[i] - '0'
		if d > 9 {
			return 0, false
		}
		v = v*10 + uint64(d)
	}
	return v, true
}
